sudo: false
branches:
  only:
  - pelican
language: python
before_install:
- locale-gen pt_BR.UTF-8
- dpkg-reconfigure locales
- update-locale LANG=pt_BR.UTF-8
- openssl aes-256-cbc -K $encrypted_160c24586979_key -iv $encrypted_160c24586979_iv -in publish-key.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git remote set-url origin git@github.com:marcoweb/marcoweb.github.io.git
- git fetch origin -f master:master
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make github